-- recipe_review, recipe_review_image 테이블은 JPA 엔티티가 없어 H2에서 자동 생성되지 않음.
-- hard delete 쿼리가 정상 실행될 수 있도록 빈 테이블만 생성.
CREATE TABLE IF NOT EXISTS recipe_review (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT
);

CREATE TABLE IF NOT EXISTS recipe_review_image (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_review_id BIGINT
);
